sglanzer/ember-cli-blanket

blueprints/ember-cli-blanket/index.js
Prior to this commit, the blanket reports were obscured by the ember
testing container. This commit adds styles to the host application's
test/index.html that raises the blanket report div above the ember
testing container so all the blanket reports can be read.
Be happy to add a test, but seems that the deps required to run the tests were removed in c72f964?
=> Add styles to place blanket reporting div above ember testing container

lib/qunit-start.js, lib/start.js
Adds a test to see if QUnit or Mocha exists. The Mocha test runner code is mostly a direct port of the blanket.js Mocha adapter. If ember-cli-mocha is installed, this should seamlessly support the Mocha test runner in addition to QUnit.
=> Update qunit-start.js to support Mocha tests

lib/blanket-loader.js
When using ember-cli-mocha and following their base install instructions qunit will no longer be present
```
npm rm ember-cli-qunit --save-dev
bower uninstall --save ember-qunit
bower uninstall --save qunit
bower uninstall --save ember-qunit-notifications
```
this protects against it's abscence
=> Guard against missing qunit when using ember-cli-mocha

blueprints/ember-cli-blanket/index.js
The template code that HTMLbars creates should not be the responsibility of the Ember Dev for code coverage. 
This removes templates from blankets coverage test. 
Cheers
=> Remove templates from coverage

index.js
@sglanzer I punted on serverMiddleware altogether for now.
it's orthogonal to the original use case of file output when running ci tests
kinda maxxed on other fronts - looks like this will keep folks running
=> Resolves #53 remove serverMiddleware

README.md, blueprints/ember-cli-blanket/files/tests/blanket-options.js, package.json, vendor/blanket-require.js, vendor/start.js
Addressing #60 by creating an autostart option in blanket-options to control the value of QUnit.config.autostart after instrumentation is complete.
=> Adding an autostart option

index.js, lib/coverage-middleware.js
Globally using the `bodyParser.json()` for an application causes any requests
with content-length > 0 to break when using `ember server --proxy ...`, the
usual symptom being that GET and DELETE requests work, but POST and PUT
requests fail:
```
Error proxying to http://192.168.2.10:9900
socket hang up
Error: socket hang up
at createHangUpError (_http_client.js:215:15)
at Socket.socketCloseListener (_http_client.js:247:23)
at Socket.emit (events.js:129:20)
at TCP.close (net.js:476:12)
```
Restricting the body parser only to the path which the coverage middleware
handles resolves this problem.
=> Enable JSON body-parser for the coverage middleware only

index.js
The serverMiddleware had been disabled because of problems when using
a http-proxy or ember-cli's proxy middleware (see #53 and #46).
Since the root cause has been resolved in #66, there's no need to hold
back this feature any longer.
This reverts commit 9b63dfd3dbf6a469fca3cf810630536d7062ee71.
=> Fix #68 by re-enabling serverMiddleware

lib/reporters/lcov-reporter.js, tests/unit/reporters/lcov-reporter-test.js
#67 contained a typo that prevents the renamer from actually working.  This PR fixes that issue to help enable #63
=> Fix renamer, lcov check was not accessing the proper object

README.md
Pretender catches every HTTP request sent sometimes without any error message.  This is pretty annoying if you don’t know where to look for why the coverage report is being sporadically created.  This is pretty tangential information and normally wouldn't belong in the docs for the library however I hope it will be included for two reasons.
1.  It's not intuitively obvious that writing a coverage report would need to send an HTTP request so it's pretty hard to reason about why this would be failing in this way.
2.  I spent something like 15 hours tracking this down and the fix was only a single line in my app code so I will feel better about myself if I get to add some documentation as well.
=> Document the coverage POST request

README.md
The option to specify a --test-page for ember-cli was added in https://github.com/ember-cli/ember-cli/pull/4377.  I took a shot at documenting this here.  
I put the options in this order because it seemed like the easiest way to test this out would be to run it one off.  I'm happy to switch them around and indicate testem.json modification first.  I'm not particularly good at writing docs (or really anything for that matter), so don't hesitate to slam my grammar and I will fix it up.
This should probably wait to be merged until ember-cli 0.2.8 is released, but I figured this would be a nice placeholder until then.  I didn't want to clutter up the readme with a 'if you're using ember-cli >= v0.2.8' statement, but let me know if that seems like a better path.
=> Document the use of the ember-cli --test-page option

lib/reporters/null-reporter.js
Null reporter wouldn't build because it was using the base Reporter's processOptions, which was expecting an outputFile be specified.
=> Fix so null reporter builds again.

index.js
We have a large repo and when it tries to make this request it fails with a 413 status code. Increasing the limit fixes this issue and I think 50mb should be sufficient for even the biggest of repositories.
=> Increase the file size limit for /write-blanket-coverage

blueprints/ember-cli-blanket/index.js
I noticed blanket currently gets put into bower's dependencies. Since it's only used for unit tests, it seems like it makes more sense to put it into devDependencies.
=> Move blanket into bower's devDependencies.

vendor/start.js
Fixes switchfly/ember-cli-mocha#61
> When I run my tests in the browser (by visiting localhost:4200/tests?coverage=true), everything works fine, but if I try to click on one of the links reported by mocha (to view that specific set of tests), the browser redirects me back to "/?grep=".
> I did a little inspecting of the HTML on the mocha test results page, and it looks like the links are being created as "href=?grep=", but I believe the correct link should be "href=/tests?grep=".
This happens when using ember-cli-mocha + ember-cli-blanket.
This was fixed by mochajs/mocha@221e0360e23a41e4b8583a22a7a5f3a3aa5f55cb and in all these related projects:
* alex-seville/blanket#356
* switchfly/ember-mocha#11
* switchfly/ember-cli-mocha#20
=> Fix tests redirecting from "/tests" to "/?grep=..."

vendor/blanket-require.js
When an addon is built a module is defined with the < addon name > that has a dependency named the name of the module plus the text of "/index" (ie. `< addon name >/index`), such as in the following:
```
define('sl-ember-components', ['sl-ember-components/index', 'ember', 'exports'], function(__index__, __Ember__, __exports__) {
'use strict';
var keys = Object.keys || __Ember__['default'].keys;
var forEach = Array.prototype.forEach && function(array, cb) {
array.forEach(cb);
} || __Ember__['default'].EnumerableUtils.forEach;
forEach(keys(__index__), (function(key) {
__exports__[key] = __index__[key];
}));
});
```
This dependency does not actually exist, which then causes the following error to be thrown in the console from the ember-cli/loader.js package:
`Error: Could not find module …
=> Resolve "Could not find module" error when used in an Ember CLI Addon

README.md, lib/reporters/lcov-reporter.js
The [node-coveralls](https://github.com/nickmerwin/node-coveralls) would crash if the report references a missing file.
So I've added a `excludeMissingFiles` option that would prevent files not existing within project's root folder from making their way into the report.
Also, returning a falsy value from the `renamer` callback would also prevent that file from appearing in the report.
PS Line numbers are still off, is this a fundamental LCOV flaw?
=> Make LCOV reporter compatible with Coveralls

.travis.yml, blueprints/ember-cli-blanket/index.js, index.js, package.json, tests/unit/exclusion-test.js, vendor/blanket-require.js, vendor/start.js
*** FOR DISCUSSION *** 
will cleanup some of the logging but otherwise this is the new `wrapModules` approach that avoids touching `require`
dependent on 
https://github.com/alex-seville/blanket/pull/545
https://github.com/ember-cli/loader.js/pull/62
some open questions - will add inline
*** DO NOT MERGE ***
=> Fixes #103, #102, and #85

README.md
With [ember-cli-mirage#281](https://github.com/samselikoff/ember-cli-mirage/pull/281) mirage shuts down its server at the end of each test.
This config should no longer be needed for apps using latest `ember-cli-mirage` and the `destroyApp` helper.
Tested on a newly created app.
=> ember-cli-mirage does not need passthrough post 0.2.0-beta.2

blueprints/ember-cli-blanket/index.js
the `addBowerPackageToProject` will join the arguments with a hash. So this actually breaks the generate command because the package commit is not found.
=> Removing extra hash in front of commit string

package.json
This PR should fix the error:
```bash
Cannot find module 'broccoli-funnel'
```
when running command:
```bash
$ ember install ember-cli-blanket
```
=> Fix pkg dependency issue

README.md
Took these from ember-cli-code-coverage. Seems to be relevant here too, as I was unable to get reports generated until I updated to these versions. Resolves #157
=> Add version requirements

index.js
With ember-cli >= 2.7 we have to take care to not drop the sourcemaps (tests.map). 
I'm definitely open to feedback on this. There might be a more elegant solution than explicitly including the `tests.map` file, such as restructuring the trees. I went with this solution because it was easy and seems low risk.
=> Fixing #159.

README.md
As this project is no longer being maintained in favor of ember-cli-code-coverage, I added a deprecation warning to the top of the README to inform other developers.
=> Added project deprecation warning to the README.
